name: Deploy Batingaw Apps to Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm ci  

      - name: Build Angular app
        run: |
          ng build --base-href /baybayin/

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.INDIGO_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          scp -o StrictHostKeyChecking=no -r ./dist/batingaw-apps/browser/* sonny@167.172.171.3:/home/sonny/tmp

      - name: Move files to web directory with sudo
        run: |
          ssh -o StrictHostKeyChecking=no sonny@167.172.171.3 "sudo mv /home/sonny/tmp/* /var/www/batingaw.com/baybayin"
